"""Creazione iniziale tabelle

Revision ID: f06a4e4d098f
Revises: 
Create Date: 2026-02-04 18:57:49.092541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06a4e4d098f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clienti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cognome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_pw', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clienti_email'), 'clienti', ['email'], unique=True)
    op.create_index(op.f('ix_clienti_id'), 'clienti', ['id'], unique=False)
    op.create_table('operatori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cognome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_pw', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operatori_email'), 'operatori', ['email'], unique=True)
    op.create_index(op.f('ix_operatori_id'), 'operatori', ['id'], unique=False)
    op.create_table('stati_segnalazione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_stati_segnalazione_id'), 'stati_segnalazione', ['id'], unique=False)
    op.create_table('segnalazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.Column('priorita', sa.Enum('BASSA', 'MEDIA', 'ALTA', name='priorita'), nullable=False),
    sa.Column('data_apertura', sa.DateTime(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_stato', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clienti.id'], ),
    sa.ForeignKeyConstraint(['id_stato'], ['stati_segnalazione.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segnalazioni_id'), 'segnalazioni', ['id'], unique=False)
    op.create_table('logs_stato_segnalazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vecchio_stato', sa.String(), nullable=True),
    sa.Column('nuovo_stato', sa.String(), nullable=False),
    sa.Column('data_modifica', sa.DateTime(), nullable=False),
    sa.Column('id_segnalazione', sa.Integer(), nullable=True),
    sa.Column('id_operatore', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_segnalazione'], ['segnalazioni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_stato_segnalazioni_id'), 'logs_stato_segnalazioni', ['id'], unique=False)
    op.create_table('messaggi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenuto', sa.Text(), nullable=False),
    sa.Column('data_invio', sa.DateTime(), nullable=False),
    sa.Column('autore', sa.String(), nullable=False),
    sa.Column('ruolo', sa.String(), nullable=False),
    sa.Column('id_segnalazione', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_segnalazione'], ['segnalazioni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messaggi_id'), 'messaggi', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messaggi_id'), table_name='messaggi')
    op.drop_table('messaggi')
    op.drop_index(op.f('ix_logs_stato_segnalazioni_id'), table_name='logs_stato_segnalazioni')
    op.drop_table('logs_stato_segnalazioni')
    op.drop_index(op.f('ix_segnalazioni_id'), table_name='segnalazioni')
    op.drop_table('segnalazioni')
    op.drop_index(op.f('ix_stati_segnalazione_id'), table_name='stati_segnalazione')
    op.drop_table('stati_segnalazione')
    op.drop_index(op.f('ix_operatori_id'), table_name='operatori')
    op.drop_index(op.f('ix_operatori_email'), table_name='operatori')
    op.drop_table('operatori')
    op.drop_index(op.f('ix_clienti_id'), table_name='clienti')
    op.drop_index(op.f('ix_clienti_email'), table_name='clienti')
    op.drop_table('clienti')
    # ### end Alembic commands ###
